- menu_name: "Services"

- name: "Contact"
  url: "https://carpentries.org/contact/"
  title: "Contact"

- name: "RSS"
  url: "/feed.xml"
  title: "Subscribe to RSS Feed"

- name: "sitemap.xml"
  url: "/sitemap.xml"
  title: "Sitemap for Google Webmaster Tools"

# - name: "Atom"
#   url: "/atom.xml"
#   title: "Subscribe to Atom Feed"
